language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
        - PRETTYNAME="Bipropellant Hoverboard API"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

script:
    - build_io_platforms


deploy:
  provider: script
  script: bash scripts/update_arduino_branch.sh
  on:
    branch: master
    repo: bipropellant/bipropellant-hoverboard-api
